namespace: soe-eda-staging
resources:
  - ../../base/namespace-staging.yaml
  - ../../base
  - ../../base/observability
  - ../../base/eda-worker
  - ../../base/integration
  - ../../base/presentation
  - ../../base/inference
labels:
  - includeSelectors: true
    pairs:
      env: staging
images:
  - name: ghcr.io/tu-org/eda-train-worker
    newTag: staging-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/integration-quarkus
    newTag: staging-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/presentation-quarkus
    newTag: staging-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/inference-service
    newTag: staging-PLACEHOLDER-SHA
patches:
  - target:
      kind: Deployment
      name: inference
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - path: namespace-overrides.yaml
  - path: patches/inference-configmap.yaml
  - path: patches/servicemonitors-namespace.yaml
