apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: soe-eda-staging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eda-cm
  namespace: soe-eda-staging
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-cm
  namespace: soe-eda-staging
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: soe-eda-staging
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: soe-eda-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-lite-ci
  namespace: soe-eda-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops-lite-apply
  namespace: soe-eda-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-lite-apply
  namespace: soe-eda-staging
