apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-lite-ci
  namespace: soe-eda-dev
  labels:
    app.kubernetes.io/part-of: soe-eda-runner
    gitops-lite: managed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitops-lite-apply
  namespace: soe-eda-dev
  labels:
    app.kubernetes.io/part-of: soe-eda-runner
    gitops-lite: managed
rules:
  - apiGroups: ["", "apps", "batch", "route.openshift.io", "*"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitops-lite-apply
  namespace: soe-eda-dev
  labels:
    app.kubernetes.io/part-of: soe-eda-runner
    gitops-lite: managed
subjects:
  - kind: ServiceAccount
    name: gitops-lite-ci
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitops-lite-apply
