resources:
  - ../../base
  - ../../base/eda-worker
  - ../../base/integration
commonLabels:
  env: dev
images:
  - name: ghcr.io/tu-org/eda-train-worker
    newTag: dev-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/integration-quarkus
    newTag: dev-PLACEHOLDER-SHA
