namespace: soe-eda-dev
resources:
  - ../../base/namespace-dev.yaml
  - ../../base
  - ../../base/observability
  - ../../base/eda-worker
  - ../../base/integration
  - ../../base/presentation
  - ../../base/inference
  - ../../base/train
labels:
  - includeSelectors: true
    pairs:
      env: dev
images:
  - name: ghcr.io/tu-org/eda-train-worker
    newTag: dev-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/integration-quarkus
    newTag: dev-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/presentation-quarkus
    newTag: dev-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/inference-service
    newTag: dev-PLACEHOLDER-SHA
patches:
  - target:
      kind: Deployment
      name: inference
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - path: patches/inference-configmap.yaml
  - path: patches/servicemonitors-namespace.yaml
  - path: patches/inference-hpa.yaml
