namespace: soe-eda-prod
resources:
  - ../../base/namespace-prod.yaml
  - ../../base
  - ../../base/observability
  - ../../base/eda-worker
  - ../../base/integration
  - ../../base/presentation
  - ../../base/inference
labels:
  env: prod
images:
  - name: ghcr.io/tu-org/eda-train-worker
    newTag: prod-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/integration-quarkus
    newTag: prod-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/presentation-quarkus
    newTag: prod-PLACEHOLDER-SHA
  - name: ghcr.io/tu-org/inference-service
    newTag: prod-PLACEHOLDER-SHA
patches:
  - target:
      kind: Deployment
      name: inference
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - path: namespace-overrides.yaml
  - path: patches/inference-configmap.yaml
  - path: patches/servicemonitors-namespace.yaml
