name: build-inference

on:
  push:
    paths:
      - "app/inference-service/**"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/inference-service:${{ github.sha }}
          docker build -t $IMAGE app/inference-service
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
      - name: Login GHCR
        if: ${{ secrets.GHCR_TOKEN != '' }}
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: echo "${GHCR_TOKEN}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push
        if: ${{ secrets.GHCR_TOKEN != '' }}
        run: docker push $IMAGE

  update-dev:
    needs: build
    if: ${{ secrets.GHCR_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update kustomize images (dev)
        run: |
          cd deploy-gitops/overlays/dev
          if ! grep -q "inference-service" kustomization.yaml; then
            printf "\nimages:\n" >> kustomization.yaml
          fi
          sed -i "s#ghcr.io.*/inference-service:.*#ghcr.io/${{ github.repository }}/inference-service:${{ github.sha }}#g" kustomization.yaml || true
          if ! grep -q "${{ github.sha }}" kustomization.yaml; then
            printf "  - name: ghcr.io/${{ github.repository }}/inference-service\n    newTag: ${{ github.sha }}\n" >> kustomization.yaml
          fi
      - name: Commit & push
        run: |
          git config user.name "ci-bot"
          git config user.email "ci@bot"
          git add deploy-gitops/overlays/dev/kustomization.yaml
          git commit -m "chore: inference image -> ${{ github.sha }}" || echo "no changes"
          git push
